/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    'tenant-settings': TenantSetting;
    media: Media;
    'consent-logs': ConsentLog;
    'ir-documents': IrDocument;
    'cv-submissions': CvSubmission;
    header: Header;
    footer: Footer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-settings': TenantSettingsSelect<false> | TenantSettingsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'consent-logs': ConsentLogsSelect<false> | ConsentLogsSelect<true>;
    'ir-documents': IrDocumentsSelect<false> | IrDocumentsSelect<true>;
    'cv-submissions': CvSubmissionsSelect<false> | CvSubmissionsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('super-admin' | 'tenant-editor' | 'tenant-viewer')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  domain: string;
  defaultLocale: 'en' | 'id';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-settings".
 */
export interface TenantSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  siteName: string;
  contactEmail?: string | null;
  contactPhone?: string | null;
  brand?: {
    /**
     * Light-coloured logo for the transparent navbar and the footer.
     */
    logoOnDark?: (number | null) | Media;
    /**
     * Dark-coloured logo for the white navbar.
     */
    logoOnLight?: (number | null) | Media;
    legalName?: string | null;
    tagline?: string | null;
    address?: string | null;
  };
  /**
   * Receives a notification for every career application to this tenant.
   */
  recruiterEmail?: string | null;
  socialLinks?:
    | {
        platform: 'linkedin' | 'instagram' | 'facebook' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  analyticsId?: string | null;
  waLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'social-share'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * UU PDP consent audit trail, written by the system. Holds no IP addresses.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-logs".
 */
export interface ConsentLog {
  id: number;
  tenant?: (number | null) | Tenant;
  timestamp: string;
  policyVersion: string;
  relatedRecordId: string;
  consentType: 'career-application' | 'contact-form';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ir-documents".
 */
export interface IrDocument {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  documentType:
    | 'annual-report'
    | 'financial-statement'
    | 'sustainability-report'
    | 'public-disclosure'
    | 'shareholder-meeting'
    | 'prospectus';
  publishedDate: string;
  locale: 'en' | 'id';
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv-submissions".
 */
export interface CvSubmission {
  id: number;
  tenant?: (number | null) | Tenant;
  submissionId: string;
  applicantName: string;
  email: string;
  phone: string;
  position: string;
  /**
   * S3 key of the résumé in the private CV bucket.
   */
  resumeFileKey: string;
  submittedAt: string;
  status: 'received' | 'reviewed' | 'shortlisted' | 'rejected';
  applicantNotifiedAt?: string | null;
  recruiterNotifiedAt?: string | null;
  externalSyncStatus: 'pending' | 'synced' | 'failed';
  externalSyncAttempts: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  tenant?: (number | null) | Tenant;
  navItems?:
    | {
        type: 'link' | 'dropdown';
        link?: {
          type: 'internal' | 'external';
          newTab?: boolean | null;
          /**
           * A page on this site, e.g. /about. No /en or /id prefix.
           */
          internalPath?: string | null;
          /**
           * A full https:// address on another site.
           */
          externalUrl?: string | null;
          label?: string | null;
        };
        label?: string | null;
        children?:
          | {
              link: {
                type: 'internal' | 'external';
                newTab?: boolean | null;
                /**
                 * A page on this site, e.g. /about. No /en or /id prefix.
                 */
                internalPath?: string | null;
                /**
                 * A full https:// address on another site.
                 */
                externalUrl?: string | null;
                label?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  showSearch?: boolean | null;
  showLanguageSwitcher?: boolean | null;
  cta?: {
    enabled?: boolean | null;
    link?: {
      type: 'internal' | 'external';
      newTab?: boolean | null;
      /**
       * A page on this site, e.g. /about. No /en or /id prefix.
       */
      internalPath?: string | null;
      /**
       * A full https:// address on another site.
       */
      externalUrl?: string | null;
      label?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tenant?: (number | null) | Tenant;
  ctaBand: {
    eyebrow?: string | null;
    heading?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    primaryButton: {
      type: 'internal' | 'external';
      newTab?: boolean | null;
      /**
       * A page on this site, e.g. /about. No /en or /id prefix.
       */
      internalPath?: string | null;
      /**
       * A full https:// address on another site.
       */
      externalUrl?: string | null;
      label?: string | null;
    };
    secondaryButton: {
      type: 'internal' | 'external';
      newTab?: boolean | null;
      /**
       * A page on this site, e.g. /about. No /en or /id prefix.
       */
      internalPath?: string | null;
      /**
       * A full https:// address on another site.
       */
      externalUrl?: string | null;
      label?: string | null;
    };
  };
  linkColumns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type: 'internal' | 'external';
                newTab?: boolean | null;
                /**
                 * A page on this site, e.g. /about. No /en or /id prefix.
                 */
                internalPath?: string | null;
                /**
                 * A full https:// address on another site.
                 */
                externalUrl?: string | null;
                label?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  partOf?: {
    enabled?: boolean | null;
    label?: string | null;
    logo?: (number | null) | Media;
    link?: {
      type: 'internal' | 'external';
      newTab?: boolean | null;
      /**
       * A page on this site, e.g. /about. No /en or /id prefix.
       */
      internalPath?: string | null;
      /**
       * A full https:// address on another site.
       */
      externalUrl?: string | null;
      label?: string | null;
    };
  };
  /**
   * Use {year} for the current year and {legalName} for the company's legal name from Tenant Settings, e.g. Copyright © {year} {legalName}. All Rights Reserved.
   */
  copyright?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-settings';
        value: number | TenantSetting;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'consent-logs';
        value: number | ConsentLog;
      } | null)
    | ({
        relationTo: 'ir-documents';
        value: number | IrDocument;
      } | null)
    | ({
        relationTo: 'cv-submissions';
        value: number | CvSubmission;
      } | null)
    | ({
        relationTo: 'header';
        value: number | Header;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  defaultLocale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-settings_select".
 */
export interface TenantSettingsSelect<T extends boolean = true> {
  tenant?: T;
  siteName?: T;
  contactEmail?: T;
  contactPhone?: T;
  brand?:
    | T
    | {
        logoOnDark?: T;
        logoOnLight?: T;
        legalName?: T;
        tagline?: T;
        address?: T;
      };
  recruiterEmail?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  analyticsId?: T;
  waLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'social-share'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-logs_select".
 */
export interface ConsentLogsSelect<T extends boolean = true> {
  tenant?: T;
  timestamp?: T;
  policyVersion?: T;
  relatedRecordId?: T;
  consentType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ir-documents_select".
 */
export interface IrDocumentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  documentType?: T;
  publishedDate?: T;
  locale?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv-submissions_select".
 */
export interface CvSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  submissionId?: T;
  applicantName?: T;
  email?: T;
  phone?: T;
  position?: T;
  resumeFileKey?: T;
  submittedAt?: T;
  status?: T;
  applicantNotifiedAt?: T;
  recruiterNotifiedAt?: T;
  externalSyncStatus?: T;
  externalSyncAttempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  tenant?: T;
  navItems?:
    | T
    | {
        type?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              internalPath?: T;
              externalUrl?: T;
              label?: T;
            };
        label?: T;
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    internalPath?: T;
                    externalUrl?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  showSearch?: T;
  showLanguageSwitcher?: T;
  cta?:
    | T
    | {
        enabled?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              internalPath?: T;
              externalUrl?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tenant?: T;
  ctaBand?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        primaryButton?:
          | T
          | {
              type?: T;
              newTab?: T;
              internalPath?: T;
              externalUrl?: T;
              label?: T;
            };
        secondaryButton?:
          | T
          | {
              type?: T;
              newTab?: T;
              internalPath?: T;
              externalUrl?: T;
              label?: T;
            };
      };
  linkColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    internalPath?: T;
                    externalUrl?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  partOf?:
    | T
    | {
        enabled?: T;
        label?: T;
        logo?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              internalPath?: T;
              externalUrl?: T;
              label?: T;
            };
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}