include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  dilm-local-cv {
    defaultVisibilityTimeout = 360 seconds
    deadLettersQueue {
      name = "dilm-local-cv-dlq"
      maxReceiveCount = 5
    }
  }
  dilm-local-cv-dlq {}
}
